name: 'changelog-parser-action'
description: 'Parse your changelog file'
author: 'ocavue'
inputs:
  filePath:
    required: false
    description: 'Path to changelog file/'
    default: 'CHANGELOG.md'
  removeMarkdown:
    required: false
    default: 'true'
    description: 'Removes the markdown markup from the changelog entries by default. You can change its value to false to keep the markdown.'
outputs:
  parsed:
    description: 'A JSON string representing the parsed changelog object. Check https://github.com/hypermodules/changelog-parser/tree/v2.8.0#standards for more information about the object structure.'

runs:
  using: 'node12'
  main: 'dist/index.js'
